### ISSUE TITLE
set_html and replace_with seems not work

### ISSUE THREAD

**Issue by 1984204066** [fefit/visdom#14]
my cargo.toml

visdom = { version = "0.5.8", features = ["insertion", "full"] }

the function do not work

fn get_images(root: &mut Elements, no: &str) {
    root.find("img").for_each(|idx, img| {
        if let Some(src) = img.get_attribute("data-src") {
            let src = src.to_string();
            let re = Regex::new("wx_fmt=([^&]*)").unwrap();
            if let Some(cap) = re.captures(&src) {
                if let Some(fmt) = cap.get(1) {
                    let ext = fmt.as_str();
                    let fname = format!("{no}-{idx}.{ext}");
                    let new_img = format!("<img src='./img/{fname}'/>");
                    // let new_img = Vis::load(new_img).unwrap();
                    // println!("{}", new_img.outer_html());
                    // let it = new_img.get_ref().iter().next().unwrap();
                    // println!("{}", it.as_ref().outer_html());
                    img.set_html(&new_img);
                    // img.as_mut().replace_with(&it);
                    // img.replace_with(it);
                    println!("1. {}", img.outer_html());
                    println!("2. {}", img.html());
                }
            }
        }
        true
    });

    ()
}

**Comment by fefit** [comment]
@1984204066 Hi, thx for the issue, i don't know the original html you used in this case, so i used the following code and had a try.
```rust
let html = r#"
	<div id="content">
		<img data-src="img/1-png?wx_fmt=png" />
		<img data-src="img/2-jpg?wx_fmt=jpg" />
	</div>
"#;
let root = Vis::load(html).unwrap();
let mut content = root.find("#content");
fn get_images(content: &mut Elements, no: &str) {
	content.find("img").for_each(|idx, img| {
		if let Some(src) = img.get_attribute("data-src") {
			let src = src.to_string();
			let re = Regex::new("wx_fmt=([^&]*)").unwrap();
			if let Some(cap) = re.captures(&src) {
				if let Some(fmt) = cap.get(1) {
					let ext = fmt.as_str();
					let fname = format!("{no}-{idx}.{ext}");
					let new_img = format!("<img src='./img/{fname}' />");
					let mut new_img = Vis::load(&new_img).unwrap();
					Vis::dom(img).replace_with(&mut new_img);
				}
			}
		}
		true
	});
}
get_images(&mut content, "abc");
println!("{}", root.outer_html());
```
the above code will ouput:
```html
<div id="content">
  <img src='./img/abc-0.png' />
  <img src='./img/abc-1.jpg' />
</div>
```
Here are some things should explain:
1. the `set_html` method is set the element's `inner_html`, `img` is a void element, so `set_html` will make no affect to it's own `html`.
2. so you should use `replace_with`, and the `replace_with` method will replace its parent's `html` with the new html by using the `set_html` method, but here is a limitation: the document-fragement root element can't use `set_html` method, maybe it's a issue should be fixed.

I hope it will fix your issue, any problem you can continue comment in this issue. thx again!

**Comment by 1984204066** [comment]
thanks for your reply,i will try later.





---Original---
From: ***@***.***&gt;
Date: Tue, Nov 29, 2022 10:53 AM
To: ***@***.***&gt;;
Cc: "Newbee ***@***.******@***.***&gt;;
Subject: Re: [fefit/visdom] set_html and replace_with seems not work (Issue#14)




 
@1984204066 Hi, thx for the issue, i don't know the original html you used in this case, so i used the following code and had a try.
 let html = r#" 	<div id="content"&gt; 		<img data-src="img/1-png?wx_fmt=png" /&gt; 		<img data-src="img/2-jpg?wx_fmt=jpg" /&gt; 	</div&gt; "#; let root = Vis::load(html).unwrap(); let mut content = root.find("#content"); fn get_images(content: &amp;mut Elements, no: &amp;str) { 	content.find("img").for_each(|idx, img| { 		if let Some(src) = img.get_attribute("data-src") { 			let src = src.to_string(); 			let re = Regex::new("wx_fmt=([^&amp;]*)").unwrap(); 			if let Some(cap) = re.captures(&amp;src) { 				if let Some(fmt) = cap.get(1) { 					let ext = fmt.as_str(); 					let fname = format!("{no}-{idx}.{ext}"); 					let new_img = format!("<img src='./img/{fname}' /&gt;"); 					let mut new_img = Vis::load(&amp;new_img).unwrap(); 					Vis::dom(img).replace_with(&amp;mut new_img); 				} 			} 		} 		true 	}); } get_images(&amp;mut content, "abc"); println!("{}", root.outer_html());
 
the above code will ouput:
 <div id="content"&gt;   <img src='./img/abc-0.png' /&gt;   <img src='./img/abc-1.jpg' /&gt; </div&gt;
 
Here are some things should explain:
  
the set_html method is set the element's inner_html, img is a void element, so set_html will make no affect to it's own html.
 
so you should use replace_with, and the replace_with method will replace its parent's html with the new html by using the set_html method, but here is a limitation: the document-fragement root element can't use set_html method, maybe it's a issue should be fixed.
  
I hope it will fix your issue, any problem you can continue comment in this issue. thx again!

**Comment by 1984204066** [comment]
Yes  use Vis::dom(img).replace_with(&mut new_img); works, great thanks.

Though
                    println!("1. {}", img.outer_html());
still output old value, ofcourse it still reasonable, because we can think calling Vis::dom changes the dom, not img itself.

But if i call this way:
                    let mut new_img = Vis::load(new_img).unwrap();
                    let it = new_img.get_ref().iter().next().unwrap();
                    println!("{}", it.as_ref().outer_html());
                    img.replace_with(it);    // takes effect after leave for_each. Delayed
                    println!("1. {}", img.outer_html());  // output old value.
When you leave the for_each, the content changed, this means  img.replace_with(it) is correct.

My question is should I expect the  img.replace_with(it); should take effect immediately,  so  println!("1. {}", img.outer_html()); should print new value?

**Comment by fefit** [comment]
@1984204066 I understand what you mean, the `replace_with` method can replace the element with not only one target elements, so it will only change the parent element but not itself, consider most people will only replace one element to another, and from the semantic, maybe it's useful to change itself too. later i will publish a new version to support it. thx your advice!

**Comment by fefit** [comment]
@1984204066 the new version v0.5.9 has published, you can have a try~

**Comment by 1984204066** [comment]
Yes, v0.5.9 solve the problem. perfectly!!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fefit/visdom"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月29日(星期二) 下午5:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fefit/visdom] set_html and replace_with seems not work (Issue #14)





 
@1984204066 the new version v0.5.9 has published, you can have a try~
