### ISSUE TITLE
这么好的项目为什么这么少人知道？

### ISSUE THREAD

**Issue by lauglam** [fefit/visdom#15]
我Google了好几天，看过html5ver/craper/lol html之类的。他们的用法非常的复杂。

原本C# 有自己的Document可以直接使用，到了Rust就找不到了，最后在简书发现了作者的项目。

真是非常棒的项目，希望能多点star，希望作者能一直维护下去（Rust好多项目已经没人维护了，悲

最后，附上诚挚的感谢！

**Comment by fefit** [comment]
@lauglam 感谢关注与鼓励，能为大家的日常开发带来一些便利就是开发者最大的动力，当然项目一定还有不完善的地方，我也将继续坚持维护好项目，再次感谢支持~！
