### ISSUE TITLE
Stripping class entirely

### ISSUE THREAD

**Issue by DjakaTechnology** [fefit/visdom#18]
Hello, thanks for the library

I'm wondering how do I remove class="" attributes? I want to remove anything that class related, but I can't know their class name.

I've tried this but it doesn't work

```
html.remove_attr("style");
html.remove_attr("class");
        ```

**Comment by fefit** [comment]
@DjakaTechnology Do you mean that you want to remove the `class` attribute of all elements with the `class` attribute? if so, you need to first find all elements with `class` attribute, then remove the attribute, some code like below:
```rust
let html = r#"
<!DOCTYP html>
<html>
  <head></head>
  <body>
    <div class="abc">
      <div class="def">div1</div>
      <div>
        <span class="g">span1</span>
      </div>
    </div>
  </body>
</html>
"#;
let root = Vis::load(html)?;
// find elements with class attribute and remote the attribute
// there are three elements with the class attribute, `abc`, `def`, `g`
assert_eq!(root.find("[class]").length(), 3);
root.find("[class]").remove_attr("class");
// all elements's `class` attribute has been removed
assert_eq!(root.find("[class]").length(), 0);
```

**Comment by fefit** [comment]
@DjakaTechnology I will close this issue, if you still have questions about this issue, feel free to reopen it.
