### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by Archimboldi** [fefit/visdom#3]
在一个loop中，使用了let doc = Vis::load(&text)，doc.find()之后，调用了doc.remove(),text.clear()
内存仍会以1~2M的速度持续增加

**Comment by fefit** [comment]
@Archimboldi 感谢反馈~能方便给出个大概的稍微详细点的示例代码吗？我先按你说的流程试试看能不能排查到问题了~

**Comment by Archimboldi** [comment]
[main.txt](https://github.com/fefit/visdom/files/7271609/main.txt)

**Comment by Archimboldi** [comment]
点错，给close了，麻烦看下代码

**Comment by fefit** [comment]
@Archimboldi 抱歉，回复晚了，刚好假期事情有点多，下午挨个排查后，发现内存没有正确释放的原因是在依赖的html parser的库中rphtml错误的用了一个Rc的循环引用，导致引用计数没法归零，内存没法释放。明天将更新一版rphtml修复这个问题，另外visdom的load方法后面以前为了写法方便，直接返回的elements可以链式操作，但实际上返回document类型比较适合你这种场景，所以这里如果改动会成break change了，预想的是 `Vis::load(html).elements()` 来代替 `Vis::load(html)`，然后 `Vis::load(html)` 返回的Document就可以增加`destory`方法主动释放文档节点树，不知道这样改使用时的修改成本高不高~？

**Comment by fefit** [comment]
@Archimboldi 已经修复啦，暂时保持了和以前一致的API，不用改动代码，有空你可以再试试跑一下代码，如还有问题欢迎随时反馈，感谢~！

**Comment by Archimboldi** [comment]
好的，谢谢啦，现在的内存表现很棒！已Star
