### ISSUE TITLE
如何获取节点的tag name（节点名称）？

### ISSUE THREAD

**Issue by zhangxianhong** [fefit/visdom#4]
非常好Rust库。
在使用过程中，遇到一个问题：遍历所有节点时，希望能获取节点的名称，从源码看有tag_name(),但没看到可调用的接口。

``` Rust
let html = r#"
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>.eq</title>
  </head>
  <body>
    <ul id="menu">
      <li class="item-1">item-1</li>
      <li class="item-2">item-2</li>
      <li class="item-3">item-3</li>
    </ul>
  </body>
</html>
"#;
let root = Vis::load(html)?;
root.each(|_index, ele|{
  println!("tag:{}", ele.tag_name()); // 如何获取tag_name
  true
})
```

**Comment by zhangxianhong** [comment]
在tests/traits.rs中找到了样例：
``` Rust
	let root = Vis::load(&html)?;
	let doc = root.document();
	assert_eq!(doc_element.unwrap().tag_name(), "HTML");
```

**Comment by fefit** [comment]
@zhangxianhong 抱歉，看到晚了，刚开始设计的时候，为了load操作方便，返回的是个包含root虚拟节点的Elements，所以在Elements上留了个document方法入口来返回document，通过document.document_element来返回HTML根节点。如果load的是正常的包含HTML根节点的html代码，可以通过这种方式来获取；如果是非HTML的DocumentFragement片段，就拿不到document_element了，对于这种情况，要拿到根节点，可能针对两种情况整体增加个:root伪类比较方便，后续可以添加下。

**Comment by fefit** [comment]
@zhangxianhong 新增了 `:root` 伪类来查找 `html` 根元素，一般情况下也可以通过标签名 `:children("html")` 来直接获取。感谢反馈！
