### ISSUE TITLE
将`Result<Elements, Box<dyn Error>>` 改为`Result<Elements, Box<dyn Error + Send>>`

### ISSUE THREAD

**Issue by zys864** [fefit/visdom#5]
可以将`Result<Elements, Box<dyn Error>>` 改为`Result<Elements, Box<dyn Error + Send>>`吗。以便与`anyhow`兼容

**Comment by fefit** [comment]
感谢建议，晚点将更新一版修改一下～

**Comment by fefit** [comment]
@zys864  0.4.12 已修改返回的错误类型为 `Box<dyn Error + Send + Sync>`，可以通过 `.map(|e|anyhow!(e))` 来转换为 `anyhow::Error`；如果使用中还有问题，欢迎随时反馈~！感谢！
