### ISSUE TITLE
Opposite of .has()

### ISSUE THREAD

**Issue by rrjanbiah** [fefit/visdom#8]
Is opposite of `has()` possible already? I tried `not()`, but that seems to check the root of element than the children.

**Comment by fefit** [comment]
Sorry, there's no method opposite to the`has()` method yet. Currently you may need do such thing like below:
```rust
let html = r#"
    <div><p></p></div>
    <div></div>
    <div></div>
"#;
let root = Vis::load(html)?;
let divs = root.find("div");
let divs_has_p = divs.has("p");
let divs_not_has_p = divs.not_in(&div_has_p);
``` 
I think i should add the `:has` pseudo selector, so you can do this by a simpler way:
```rust
let div_not_has_p = divs.not(":has(p)");
```
I will add that later, thx for your feedback.

**Comment by rrjanbiah** [comment]
@fefit Thank you so much for your quick reply. Much appreciated!

**Comment by fefit** [comment]
@rrjanbiah The `:has` pseudo selector has been added in the new version `0.5.2`, examples can be seen in the test case function `test_selector_pseudo_has` [https://github.com/fefit/visdom/blob/main/tests/selector.rs#L829](https://github.com/fefit/visdom/blob/main/tests/selector.rs#L829). Thx again for your feedback :)

**Comment by rrjanbiah** [comment]
@fefit So fast.. thank you so much for the great library!
